@extends('layouts.app')

@section('content')
    <div class='container txt-style-intro'>
        <br><p style="font-size: 40px;"><b>NECESIDADES NUTRICIONALES EN LA INFANCIA</b></p><br>
        <p class="text-justify mt-5">¿Por qué es tan importante la nutrición infantil? Porque las necesidades nutricionales en la infancia son elevadas y al mismo tiempo el riesgo de deficiencias puede ser mayor. Porque el organismo del niño aún no está maduro y los desequilibrios tienen una mayor repercusión pudiendo provocar alteraciones irreversibles. Porque determina los hábitos alimentarios, que serán difíciles de cambiar en el futuro. Y por último, porque una alimentación sana es sinónimo de bienestar, de correcto crecimiento y desarrollo del niño.</p>
        <p class="text-justify mt-5">La alimentación de los más pequeños es tal vez la más controlada, porque los conocimientos sobre sus necesidades nutricionales son superiores a los que se tienen sobre las necesidades de otras edades.</p>
        <p class="text-justify mt-5">El crecimiento requiere aportes importantes de nutrientes. Tanto los excesos como las carencias pueden ser causa de problemas en la infancia y en edades posteriores. Diferentes estudios demuestran que los niños necesitan consumir más nutrientes pero con una cantidad inferior de calorías. Si un niño recibe una alimentación igual en cantidad y calidad a la del adulto, alcanzará un exceso calórico susceptible de desencadenar un proceso de obesidad. En cambio, si consume los mismos alimentos pero en menor proporción, los aportes vitamínicos y minerales serán insuficientes produciéndose problemas de crecimiento y desarrollo.</p>
        <br><img src="{{asset('img/menu/Infantil/ninios1.png')}}" style="width: 80%;"/><br>
        <br><p style="font-size: 40px;"><u>Distribución de las comidas</u></p>
        <p class="text-justify mt-5">La distribución de las comidas o del aporte calórico en la dieta infantil es característica: se recomiendan 5 tomas para los más pequeños (20% en el desayuno, 10-15% a media mañana, 25-30% en la comida, 10-15% en la merienda y 25% en la cena) e ir pasando paulatinamente a 4 tomas al día como para el resto de la población (25% en el desayuno, 30% en la comida, 15% en la merienda y 30% en la cena). Debemos tener en cuenta que el aparato digestivo de los niños funcionará mejor con pequeñas cantidades de alimentos repartidas a lo largo del día. Tampoco debe estar sin comer durante largos períodos de tiempo, porque su metabolismo no está capacitado para el ayuno.</p>
        <br><p style="font-size: 40px;"><u>Aporte de nutrientes</u></p>
        <p class="text-justify mt-5">Las pautas de alimentación infantil exigen una alimentación variada. En la infancia deben evitarse las dietas restrictivas (vegetariana, disociada, etc.) El niño debe comer los diferentes tipos de alimentos de cada grupo aunque en raciones moderadas.</p>
        <p class="text-justify mt-5"><b>Lácteos:</b> La leche y los productos lácteos desnatados no son recomendables durante la infancia ya que pueden dar lugar a deficiencias en vitaminas liposolubles o ácidos grasos esenciales y a un escaso aporte calórico.</p>
        <p class="text-justify mt-5"><b>Proteínas: </b>La alimentación infantil debe ser rica en proteínas. Únicamente tendrán que ser controladas si existe algún problema asociado: alergias alimentarias u otras enfermedades.</p>
        <p class="text-justify mt-5"><b>Vitaminas y minerales</b> La obesidad y el sedentarismo en los más pequeños pueden estar relacionados con aportes incorrectos de vitaminas y minerales, imprescindibles para el mantenimiento del crecimiento y de la capacidad funcional.</p>
        <p class="text-justify mt-5">El calcio es fundamental para conseguir una óptima mineralización ósea (su aporte condicionará también, parcialmente, las probabilidades de padecer osteoporosis en la edad adulta) y para prevenir la caries y otros problemas periodontales. En el período de crecimiento rápido (primer año de vida y adolescencia) se requiere entre dos y cuatro veces más calcio/kg que en la etapa adulta. Son los lácteos los encargados de aportar la cantidad necesaria de este mineral.</p>
        <br><img src="{{asset('img/menu/Infantil/ninios2.png')}}" style="width: 80%;"/><br>
        <p class="text-justify mt-5">En zonas con agua no fluorada se considera correcto un suplemento de flúor por vía sistémica antes de la erupción dental (nunca antes de los 6 meses), como estrategia para prevenir la aparición de caries desde edades tempranas.</p>
        <p class="text-justify mt-5">La vitamina D debe controlarse en lugares poco soleados o en niños que se encuentran hospitalizados o en casa debido a problemas de salud. La piel expuesta al sol es la que permite la síntesis de esta vitamina, imprescindible para la absorción y el depósito de calcio en los huesos.</p>
        <p class="text-justify mt-5">El hierro es el mineral que permite el rápido crecimiento de los niños. La introducción de la carne en la dieta durante la primera infancia contribuye a evitar la anemia en edades posteriores.</p>
        <p class="text-justify mt-5">Excepto en el caso del flúor, los suplementos nutricionales sólo están justificados en niños con carencias diagnosticadas de determinados nutrientes. En cualquier caso, si existe suplementación, nunca deberá llegarse al límite máximo para el que se ha demostrado seguridad, teniendo un especial cuidado con las vitaminas liposolubles.</p>
        
    </div>
@endsection

