@extends('layouts.app')

@section('content')
    <div class='container txt-style-intro'>

   
        <p class="text-justify mt-5">Es bien conocido por todos que la afirmación <i><b>«la mujer embarazada ha de comer por dos»</b></i> no es casi nunca cierta. Pero lo que sí es cierto es que la mujer embarazada y la lactante deben seguir unas recomendaciones dietéticas que se refieren tanto a la cantidad como a la calidad de los alimentos que debe ingerir. El mantenimiento de una alimentación correcta durante el embarazo y la lactancia son esenciales para conseguir una salud óptima del futuro hijo y la propia madre, así como para aliviar algunos de los trastornos frecuentes durante el embarazo.</p>
        <br><img src="{{asset('img/menu/EyL/embarazada1.png')}}" style="width: 80%;"/><br>
        <p class="text-justify mt-5">El embarazo y la lactancia son estados fisiológicos en los que se producen importantes cambios biológicos y metabólicos que suponen un gran desgaste físico para la mujer, y que pueden incluso influir de forma definitiva en su salud. Es evidente que la formación del nuevo ser va a requerir un aporte extra de nutrientes, que proceden tanto de los alimentos que ingiere la madre como de sus propias reservas corporales. Se puede afirmar con total certeza que <b>la dieta de la madre tiene una gran influencia sobre la salud del bebé</b> a corto plazo y muy probablemente también a largo plazo. En el período previo y por supuesto a lo largo de todo el embarazo es necesario mantener una dieta sana y variada que garantice un suministro regular y suficiente de nutrientes al feto. El cuidado de la alimentación durante el embarazo es también crucial para mantener un buen estado de salud en la madre y evitar un desgaste nutricional que puede tener consecuencias y causar entre otros trastornos anemia y descalcificación ósea.</p>
        <p class="text-justify mt-5">Aunque la necesidad de una alimentación sana durante el embarazo y la lactancia parezca una afirmación obvia, la malnutrición es una situación que se presenta con frecuencia en muchas mujeres. En nuestro país por ejemplo son relativamente frecuentes los excesos y la sobreaalimentación, que generan un desequilibrio a causa de la ingesta excesiva de azúcares y grasas, mientras que la de vitaminas, minerales y fibra alimentaria suele ser insuficiente. En cambio, <b>las carencias nutricionales que pueden repercutir gravemente en el desarrollo del feto</b>, se dan raramente en los países desarrollados pero muy frecuentemente en los países en vías de desarrollo.</p>
        <br><p style="font-size: 40px;"><u>Necesidades nutricionales</u></p><br>
        <p class="text-justify mt-5">Durante el embarazo, las necesidades nutricionales aumentan, ya que la dieta debe proporcionar suficiente energía y nutrientes para:</p>
        <ul class="text-left">
            <li>­Satisfacer los requerimientos nutricionales de la madre.</li>
            <li>Permitir el crecimiento de estructuras como el útero, la placenta y los pechos</li>
            <li>Satisfacer las necesidades para el crecimiento del feto.</li>
            <li>Permitir a la madre acumular las reservas necesarias para el crecimiento del feto y para la lactancia después del parto.</li>
        </ul>
        <p class="text-justify mt-5">Al igual que el oxígeno, los nutrientes pasan desde la placenta al feto gracias al cordón umbilical. En cuanto a la distribución de las necesidades, <b>durante los primeros meses del embarazo</b> la mayor parte de las mujeres no necesitan comer más de lo normal, ya que <b>el organismo se vuelve mucho más eficiente para absorber y utilizar los nutrientes a partir de los alimentos</b> (por ejemplo, los requerimientos de calcio pueden satisfacerse enteramente si la dieta se ajusta a las recomendaciones [800 mg/día] y se obtienen cantidades suficientes de vitamina D necesaria para la absorción intestinal del calcio por exposición a la luz del sol o a través de los alimentos). En cambio, a partir de las 20 semanas de embarazo, el aumento de tamaño del feto es considerable y se incrementa la demanda de nutrientes. Las reservas que la madre ha acumulado durante los primeros meses del embarazo se movilizan a partir de entonces para satisfacer las necesidades del feto. En los últimos meses, el feto acumula proteínas y grasa, aumentando al mismo tiempo la demanda de calcio y fósforo a causa del desarrollo del esqueleto.</p>
        <br><img src="{{asset('img/menu/EyL/embarazada2.png')}}" style="width: 80%;"/><br>
        <br><p style="font-size: 40px;"><u>Necesidades enérgeticas</u></p><br>
        <p class="text-justify mt-5">Durante el embarazo debe producirse un aumento paulatino de la ingesta energética total. En el segundo trimestre se recomienda incrementar la ingesta en 200 kcal por día. En los últimos 3 meses del embarazo los requerimientos de energía aumentan 300 kcal por día. En este período, el gasto energético para la realización de actividad física es generalmente menor. Si la madre no ingiere suficientes alimentos y sus reservas lipídicas son bajas, el feto crece más lentamente y el niño puede tener bajo peso al nacer. En la mujer lactante se recomienda aumentar la ingesta energética total en 500 kcal al día2.</p>
        <p class="text-justify mt-5"><b>Proteínas: </b>Las proteínas son nutrientes con una función esencialmente plástica, imprescindibles para la formación del feto y para permitir el crecimiento de estructuras maternas como el útero. La ingestión de alimentos ricos en proteínas debe aumentar principalmente en los 3 últimos meses del embarazo, de forma que una restricción en este período puede repercutir en el crecimiento fetal.</p>
        <p class="text-justify mt-5"><b>Hidratos de carbono: </b>La principal función de los hidratos de carbono o glúcidos es la de proporcionar energía. Las recomendaciones respecto a su ingesta no varían durante el embarazo o la lactancia, y deben ser por tanto la principal fuente de energía para la mujer gestante o lactante (50-60% de la energía total).Hay dos tipos de glúcidos en la dieta: los glúcidos simples o azúcares, y los glúcidos complejos, el más importante de los cuales es el almidón. La cantidad de azúcares o glúcidos de digestión rápida no debe exceder el 10% de las kilocalorías totales, lo que equivale a unos 50 g de azúcar (unos 10 terrones). Se recomienda, sobre todo, vigilar la ingesta de bebidas y refrescos azucarados (un vaso de una bebida de cola o gaseosa aportan 25 g de azúcar) y tomar en todo caso el azúcar o dulces al final de las comidas en lugar de entre comidas o en ayunas, ya que en estas condiciones la sacarosa se comporta como un glúcido de digestión lenta. También hay que evitar la ingesta excesiva de fruta, que aporta cantidades de azúcar (fructosa) importantes.</p>
        <p class="text-justify mt-5"><b>Lípidos: </b>Durante la gestación se deben seguir las recomendaciones generales sobre la ingestión de lípidos que se realizan a la población normal, es decir, controlar la ingestión de lípidos de origen animal, que proporcionan ácidos grasos saturados, y aumentar los lípidos de origen vegetal, que proporcionan ácidos grasos poliinsaturados (como el linoleico y el linolénico, compuestos esenciales para el hombre, ya que no los puede sintetizar y deben ser ingeridos en la dieta).</p>
        <br><img src="{{asset('img/menu/EyL/embarazada4.png')}}" style="width: 80%;"/><br> 
        <p class="text-justify mt-5"><b>Calcio: </b>Durante el embarazo se produce un paso activo de calcio de la madre al feto a través de la placenta. El calcio, que es necesario para la formación del esqueleto, procede de los alimentos que ingiere de la madre y de sus propias reservas óseas de calcio. Para evitar un desgaste excesivo de las reservas de calcio de la madre es imprescindible asegurar un correcto aporte de este mineral en la dieta. Se estima que las necesidades de calcio en la mujer lactante son de unos 1.200 mg/día, muy superiores a los de la mujer adulta.</p>
        <p class="text-justify mt-5"><b>Hierro: </b>En principio, los requerimientos de hierro de la mujer embarazada pueden satisfacerse por medio de la dieta. Sin embargo, el médico puede prescribir suplementos de hierro para aquellas mujeres que desarrollen anemia por déficit de hierro, ya que la anemia puede causar bajo peso del niño al nacer o provocar que éste desarrolle un déficit de hierro durante el primer o segundo año de vida.</p>
        <p class="text-justify mt-5"><b>Ácido Fólico: </b>Una ingesta adecuada de ácido fólico es fundamental en el período preconcepcional y hasta la duodécima semana de embarazo, ya que esta vitamina es esencial para la prevención de los defectos del tubo neuronal en el recién nacido. Es por ello que durante el primer trimestre de embarazo se recomienda tomar suplementos de ácido fólico de 400 µg/día. Muchos autores recomiendan, además, la suplementación con ácido fólico durante todo el embarazo en el caso de mujeres con síntomas de malnutrición, embarazo múltiple o que padecen anemia. Asimismo, se recomienda en todos los casos la ingesta de alimentos ricos en ácido fólico, como son las verduras (brécol, coliflor, acelgas, espinacas), las legumbres (garbanzos) y frutas.</p>
        <p class="text-justify mt-5"><b>Vitamina A: </b>Esta vitamina es esencial para una buena salud, y sus requerimientos aumentan, de hecho, durante el embarazo y la lactancia. Sin embargo, ingestas muy elevadas de esta vitamina se han asociado a defectos en el recién nacido. Es por eso que se recomienda que las mujeres embarazadas no tomen suplementos de vitamina A si no es bajo supervisión del médico. En lo que respecta a la alimentación, se recomienda no abusar de ciertos alimentos como el hígado y el paté, ya que contienen cantidades muy elevadas de esta vitamina.</p>
        <p class="text-justify mt-5"><b>Vitamina D: </b>Está íntimamente relacionada con el calcio, y es también esencial para el desarrollo óseo del niño. Entre los alimentos más ricos en vitamina D se encuentran el pescado (salmón, sardinas y arenques) y los huevos, aunque en nuestro país la principal fuente de vitamina D sigue siendo la exposición controlada a la luz del sol.</p>
        <p class="text-justify mt-5"><b>Alcohol: </b>La mujer embarazada debe evitar el alcohol, ya que las bebidas alcohólicas pueden llegar a producir daños graves en el feto.</p>
        <br><img src="{{asset('img/menu/EyL/embarazada3.png')}}" style="width: 80%;"/><br> 
    </div>
@endsection
